export const UserActionTypes = {
  SET_CURRENT_USER: 'SET_CURRENT_USER',

  SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
  SIGN_IN_FAILURE: 'SIGN_IN_FAILURE',

  GOOGLE_SIGN_IN_START: 'GOOGLE_SIGN_IN_START',
  EMAIL_SIGN_IN_START: 'EMAIL_SIGN_IN_START',

  CHECK_USER_SESSION: 'CHECK_USER_SESSION'
}